#!/usr/bin/env python3
"""Generate WireGuard split-tunnel config to bypass the VPN for Google Meet.

Fetches Google's published IP ranges and generates a helper script plus
PostUp/PreDown hooks. This keeps AllowedIPs = 0.0.0.0/0 intact (preserving
wg-quick's proper default-route handling with fwmark) while routing Google
traffic directly through the real gateway.

Usage:
    python3 generate-split-tunnel.py CONFIG    # update .conf and create helper script
"""

import argparse
import ipaddress
import json
import os
import re
import stat
import sys
import urllib.request


GOOGLE_IP_RANGES_URL = "https://www.gstatic.com/ipranges/goog.json"


def fetch_google_ranges():
    """Fetch Google's published IPv4 ranges (covers Meet, etc.)."""
    req = urllib.request.Request(GOOGLE_IP_RANGES_URL)
    with urllib.request.urlopen(req, timeout=15) as resp:
        data = json.loads(resp.read())

    nets = []
    for prefix in data["prefixes"]:
        if "ipv4Prefix" in prefix:
            nets.append(ipaddress.ip_network(prefix["ipv4Prefix"]))
    return sorted(nets)


def generate_helper_script(ranges):
    """Generate a shell script that adds/removes routes for Google ranges."""
    cidrs = " ".join(str(n) for n in ranges)
    return f"""\
#!/bin/bash
# Auto-generated by generate-split-tunnel.py
# Routes Google IP ranges outside the WireGuard tunnel.
set -euo pipefail

ACTION="${{1:-up}}"

# Detect the default gateway (still in main table when PostUp runs).
GATEWAY=$(ip route show default | awk '/default/ {{print $3; exit}}')
DEV=$(ip route show default | awk '/default/ {{print $5; exit}}')

if [ -z "$GATEWAY" ] || [ -z "$DEV" ]; then
    echo "ERROR: could not detect default gateway" >&2
    exit 1
fi

CIDRS="{cidrs}"

for CIDR in $CIDRS; do
    if [ "$ACTION" = "up" ]; then
        ip route add "$CIDR" via "$GATEWAY" dev "$DEV" 2>/dev/null || true
    else
        ip route del "$CIDR" via "$GATEWAY" dev "$DEV" 2>/dev/null || true
    fi
done
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "config",
        help="WireGuard .conf file to update",
    )
    args = parser.parse_args()

    print("Fetching Google IP ranges...", file=sys.stderr)
    google_ranges = fetch_google_ranges()
    print(f"  Found {len(google_ranges)} IPv4 prefixes to exclude", file=sys.stderr)

    # Write the helper script next to the config
    config_dir = os.path.dirname(os.path.abspath(args.config))
    helper_path = os.path.join(config_dir, "google-bypass.sh")
    # PostUp/PreDown reference /etc/wireguard/ since that's where wg-quick runs from
    helper_ref = "/etc/wireguard/google-bypass.sh"

    with open(helper_path, "w") as f:
        f.write(generate_helper_script(google_ranges))
    os.chmod(helper_path, os.stat(helper_path).st_mode | stat.S_IEXEC)
    print(f"  Wrote {helper_path}", file=sys.stderr)

    # Update the WireGuard config
    with open(args.config) as f:
        config = f.read()

    # Ensure AllowedIPs is 0.0.0.0/0
    config = re.sub(
        r"(AllowedIPs\s*=\s*).*",
        r"\g<1>0.0.0.0/0",
        config,
    )

    # Remove any existing google-bypass PostUp/PreDown lines
    config = re.sub(r"PostUp\s*=\s*.*google-bypass.*\n", "", config)
    config = re.sub(r"PreDown\s*=\s*.*google-bypass.*\n", "", config)

    # Add PostUp/PreDown in the [Interface] section (NOT [Peer])
    hooks = (
        f"PostUp = {helper_ref} up\n"
        f"PreDown = {helper_ref} down"
    )
    # Insert hooks before the [Peer] section
    if "[Peer]" in config:
        config = config.replace("[Peer]", f"{hooks}\n\n[Peer]", 1)
    else:
        config += f"\n{hooks}\n"

    with open(args.config, "w") as f:
        f.write(config)
    print(f"  Updated {args.config}", file=sys.stderr)
    print("Done. Restart WireGuard to apply.", file=sys.stderr)


if __name__ == "__main__":
    main()
